"""Can a sound-state reading calibrate the model-form offset away?

`cross_solver.py` prices the largest line in the error budget: read a field
generated by a structurally different concrete model, and the zero point of
the identification moves by twenty-seven per cent of the section. That line
is quoted as irreducible because no strain measurement reduces it. The
qualifier matters, though: it is irreducible by measuring *more strain*, not
necessarily by measuring *somewhere else*.

The identifying condition is affine and the alien model's concrete carries a
tension the cracked-membrane map sets to zero, so the offset enters as a
single unknown force,

    T(theta) = T_c + rho_tie (1 - theta) S ,

with T_c the concrete contribution. A zone of the same member known to be
sound supplies one equation in that one unknown, and if T_c is a property of
the concrete rather than of the state, carrying it into a deteriorated zone
removes the offset without any knowledge of the alien model at all.

This module tests that. It identifies T_c from the theta = 0 field of each
alien family and re-runs the identification on the remaining four states
with T_c carried across, comparing against the uncalibrated result. It also
reports how far T_c drifts across the states, which is what decides whether
the route survives on a real structure where the sound zone is a different
part of the member rather than the same part at an earlier time.

Run:  python model_family_calibration.py   (writes figures/model_family_cal.json)
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent / "oracle"))

import figdata as FD                                                       # noqa: E402
from problem import DeepBeam                                               # noqa: E402
from recover_utils import element_strains, bracket_root                    # noqa: E402

ORACLE = HERE.parent / "oracle"
OUT = HERE.parent / "figures" / "model_family_cal.json"
DELTA = "3.5"
THETA = [0.0, 0.10, 0.20, 0.30, 0.40]
WIDE = np.linspace(-0.70, 0.70, 281)


def couple_curve(prob, area, xy, u, grid):
    """Band tension, lever arm and couple at every trial value on the grid."""
    cx, cy, ex, ey, gxy = element_strains(xy, u, FD.NX, FD.NY)
    T, z, C = [], [], []
    for g in grid:
        t, zz, c = FD.band_couple(prob, cx, cy, ex, ey, gxy, area, g)
        T.append(t); z.append(zz); C.append(c)
    return np.array(T), np.array(z), np.array(C)


def run(name, states, arms):
    prob = DeepBeam()
    area = (prob.L / FD.NX) * (prob.H / FD.NY) / 2.0
    rows = []
    for (th, xy, u, lam), arm in zip(states, arms):
        T, z, C = couple_curve(prob, area, xy, u, WIDE)
        m_req = (lam * prob.P / 2.0) * (FD.X_CUT - arm) / 1e6
        rows.append(dict(theta=th, lam=lam, arm=arm, m_req=m_req,
                         T=T, z=z, C=C))

    # the sound state supplies T_c: the tension the map is missing there
    s = rows[0]
    i0 = int(np.argmin(np.abs(WIDE - 0.0)))
    Tc = (s["m_req"] - s["C"][i0]) * 1e3 / s["z"][i0]                 # kN

    out = []
    for r in rows:
        raw = bracket_root(r["C"] - r["m_req"], WIDE)
        cal = bracket_root((r["T"] + Tc) * r["z"] / 1e3 - r["m_req"], WIDE)
        # what T_c would have had to be at this state for an exact answer
        j = int(np.argmin(np.abs(WIDE - r["theta"])))
        Tc_state = (r["m_req"] - r["C"][j]) * 1e3 / r["z"][j]
        out.append(dict(theta_true=r["theta"], lam=r["lam"],
                        arm_mm=r["arm"], m_req_kNm=r["m_req"],
                        theta_raw=float(raw), err_raw_pp=(raw - r["theta"]) * 100,
                        theta_cal=float(cal), err_cal_pp=(cal - r["theta"]) * 100,
                        Tc_required_kN=float(Tc_state)))
    return dict(name=name, Tc_from_sound_kN=float(Tc), rows=out)


def load_cross(tag, fname):
    d = np.load(ORACLE / fname)
    st = [(th, d["xy"], d[f"u_{tag}_{th:.2f}_{DELTA}"],
           float(d[f"lam_{tag}_{th:.2f}_{DELTA}"][0])) for th in THETA]
    arms = [float(d[f"chk_x_reaction_mm_{tag}_{th:.2f}_{DELTA}"][0])
            for th in THETA]
    return st, arms


def main() -> None:
    fams = []
    for name, tag, fname in [
            ("fixed crack, Q4 40x20", "40x20", "fields_crossmodel.npz"),
            ("regularized fixed crack, Q4 40x20", "40x20",
             "fields_crossmodel_reg.npz")]:
        st, arms = load_cross(tag, fname)
        fams.append(run(name, st, arms))

    for f in fams:
        print(f"\n{f['name']}")
        print(f"  T_c identified on the sound state: {f['Tc_from_sound_kN']:.1f} kN")
        print(f"{'theta':>7}{'raw':>9}{'err pp':>9}"
              f"{'calibrated':>12}{'err pp':>9}{'T_c needed':>12}")
        for r in f["rows"]:
            print(f"{r['theta_true']:>7.2f}{r['theta_raw']:>9.4f}"
                  f"{r['err_raw_pp']:>+9.1f}{r['theta_cal']:>12.4f}"
                  f"{r['err_cal_pp']:>+9.1f}{r['Tc_required_kN']:>12.1f}")
        e = [abs(r["err_cal_pp"]) for r in f["rows"][1:]]
        e0 = [abs(r["err_raw_pp"]) for r in f["rows"][1:]]
        tc = [r["Tc_required_kN"] for r in f["rows"]]
        print(f"  deteriorated states: mean |error| {np.mean(e0):.1f} pp raw, "
              f"{np.mean(e):.1f} pp calibrated")
        print(f"  T_c across the states: {min(tc):.1f} to {max(tc):.1f} kN "
              f"(spread {100*(max(tc)-min(tc))/np.mean(tc):.0f} % of its mean)")
        f["summary"] = dict(mean_abs_err_raw_pp=float(np.mean(e0)),
                            mean_abs_err_cal_pp=float(np.mean(e)),
                            Tc_min_kN=float(min(tc)), Tc_max_kN=float(max(tc)),
                            Tc_spread_pct=float(100 * (max(tc) - min(tc))
                                                / np.mean(tc)))
    OUT.write_text(json.dumps(
        {"what": "sound-state calibration of the model-form offset",
         "route": "T_c identified where theta is known to be zero, carried "
                  "into the deteriorated states as a constant",
         "families": fams}, indent=1))
    print(f"\nwrote {OUT}")


if __name__ == "__main__":
    main()
