"""Candidate fix 2: stop neglecting concrete tension in the identification.

The cross-solver test (cross_solver.py) leaves the sensitivity of the
identification almost intact on fields generated by a structurally different
model -- fitted slope 0.770 against 0.832 for the same-solver reference --
and destroys the zero point: intercept -0.278 against -0.009. The stated
mechanism is that the alternative field carries concrete tension the CSFM
constitutive map does not represent, so the map under-computes the band
tension the field's own statics requires and the reconciliation has to reach
for negative section loss to close.

This module tests the direct fix: put concrete tension back into the
identification. Two versions.

  tcm     the tension chord model of Marti et al. (1998) as already
          implemented in tcm.py, at the bond and crack spacing taken from
          the source. Its increment collapses once the bar yields.

  beta    an average band tensile stress sigma_ct = beta_ts f_ct, swept.
          The tensile strength offered is the one the generating structure
          actually has, f_ct = 0.33 sqrt(f_c) = 1.81 MPa (the fixed-crack
          oracle's FCT), and, separately, the EN 1992 value
          f_ctm = 0.30 f_c^(2/3) = 2.90 MPa that the study's own beta check
          used, so the two conventions are never silently mixed.

Everything else is the identification unchanged: the same 50 mm measurement
grid, the same constant-strain kinematics, the same cut at x = 700 mm, the
same 100 mm strip, the same 370 mm reaction arm, the same widened trial
range [-0.70, 0.70], and every root taken with recover_utils.bracket_root.

The 80x40 fixed-crack family is excluded throughout: its load factor rises
with deterioration, which is unphysical, and no conclusion may rest on it.

Run:  python tension_fix.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import torch

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent / "oracle"))

import figdata as FD                                                      # noqa: E402
import tcm as TCM                                                         # noqa: E402
from csfm_constitutive import membrane                                    # noqa: E402
from identify import rho_x_of_theta                                       # noqa: E402
from problem import DeepBeam                                              # noqa: E402
from recover_utils import bracket_root, element_strains                   # noqa: E402

ORACLE = HERE.parent / "oracle"
OUT = HERE.parent / "figures" / "tension_fix.json"

ARM = 370.0
DELTA = "3.5"
THETA = [0.0, 0.10, 0.20, 0.30, 0.40]
WIDE = np.linspace(-0.70, 0.70, 141)        # the trial range cross_solver uses

FCT_STRUCT = 0.33 * 30.0 ** 0.5             # 1.807 MPa, the oracle's own FCT
FCT_EN = 0.30 * 30.0 ** (2.0 / 3.0)         # 2.896 MPa, EN 1992 f_ctm


# ----------------------------------------------------------------------
# the identifying quantity, with a tension model bolted on
# ----------------------------------------------------------------------
def cut_sx(prob, cx, cy, ex, ey, gxy, theta, mode, beta=0.0, f_ct=FCT_EN,
           gate="stress"):
    """sigma_x on the cut strip, with the chosen band tension model added."""
    sel = np.abs(cx - FD.X_CUT) < FD.BAND_W
    X = torch.tensor(cx[sel]).unsqueeze(-1)
    Y = torch.tensor(cy[sel]).unsqueeze(-1)
    rho = rho_x_of_theta(prob, X, Y, torch.tensor(float(theta)))
    st = membrane(torch.tensor(ex[sel]).unsqueeze(-1),
                  torch.tensor(ey[sel]).unsqueeze(-1),
                  torch.tensor(gxy[sel]).unsqueeze(-1),
                  rho, prob.rho_y(X, Y), prob.mat, soften=True)
    sx = st["sigma_x"].squeeze().numpy().copy()
    ys = cy[sel]
    inb = ys < FD.BAND
    if mode == "tcm":
        inc, _s, _sr, _ck = TCM.tcm_increment(
            ex[sel][inb], rho.squeeze().numpy()[inb], theta, prob.mat, f_ct,
            TCM.PHI_0, TCM.LAM_S)
        sx[inb] = sx[inb] + inc
    elif mode == "beta":
        # where the concrete of the band is taken to be carrying tension:
        # "stress" is the study's own convention in tension_chord.py, "strain"
        # is the physically stated one (concrete in tension where eps_x > 0)
        on = (sx[inb] > 0.0) if gate == "stress" else (ex[sel][inb] > 0.0)
        sx[inb] = sx[inb] + beta * f_ct * on
    return sx, ys


def couple(prob, s, area, theta, **kw):
    """Tie resultant, lever arm and their couple (kN m)."""
    sx, ys = cut_sx(prob, *s, theta, **kw)
    dA = area / (2.0 * FD.BAND_W) * prob.t
    inb = ys < FD.BAND
    T = float((sx[inb] * dA).sum()) / 1e3
    wT = np.clip(sx[inb], 0.0, None)
    wC = np.clip(-sx[~inb], 0.0, None)
    yT = float((wT * ys[inb]).sum() / max(wT.sum(), 1e-9))
    yC = float((wC * ys[~inb]).sum() / max(wC.sum(), 1e-9))
    return T, yC - yT, T * (yC - yT) / 1e3


def recover(prob, s, area, lam, grid=WIDE, arm=ARM, **kw):
    """Root of the band couple against statics, by bracket_root."""
    M_req = lam * prob.P / 2.0 * (FD.X_CUT - arm) / 1e6
    f = np.array([couple(prob, s, area, g, **kw)[2] - M_req for g in grid])
    return bracket_root(f, grid), M_req, f


# ----------------------------------------------------------------------
def affine(true, rec):
    """Fitted slope and intercept of recovered against true, both fits."""
    t = np.array([a for a, b in zip(true, rec) if b is not None
                  and np.isfinite(b)], float)
    r = np.array([b for b in rec if b is not None and np.isfinite(b)], float)
    out = {"n": int(t.size)}
    if t.size >= 2:
        s, i = np.polyfit(t, r, 1)
        out.update(slope=float(s), intercept=float(i))
    m = t > 0.0
    if m.sum() >= 2:
        s, i = np.polyfit(t[m], r[m], 1)
        out.update(slope_nz=float(s), intercept_nz=float(i))
    return out


def run(states, prob, area, label, **kw):
    """One variant on one family: recovery at every state, then the fit."""
    rec, mono = [], True
    for th, s, lam in states:
        root, _m, _f = recover(prob, s, area, lam, **kw)
        rec.append(None if not np.isfinite(root) else float(root))
    ok = [v for v in rec if v is not None]
    mono = all(b > a for a, b in zip(ok, ok[1:])) and len(ok) == len(rec)
    fit = affine([th for th, _, _ in states], rec)
    n_adm = sum(1 for v in rec if v is not None and v >= 0.0)
    return {"label": label, "rec": rec, "fit": fit, "monotone": bool(mono),
            "n_admissible_nonneg": int(n_adm), "kw": {
                k: (v if not isinstance(v, float) else float(v))
                for k, v in kw.items()}}


# ----------------------------------------------------------------------
# the two families of fields
# ----------------------------------------------------------------------
def load_same_solver(delta=DELTA):
    d = np.load(ORACLE / "fields_theta.npz")
    st = []
    for th in THETA:
        s = element_strains(d["xy"], d[f"u_{th:.2f}_{delta}"], FD.NX, FD.NY)
        st.append((th, s, float(d[f"lam_{th:.2f}_{delta}"][0])))
    return st


def load_cross(tag="40x20", delta=DELTA, fname="fields_crossmodel.npz"):
    d = np.load(ORACLE / fname)
    st = []
    for th in THETA:
        s = element_strains(d["xy"], d[f"u_{tag}_{th:.2f}_{delta}"],
                            FD.NX, FD.NY)
        st.append((th, s, float(d[f"lam_{tag}_{th:.2f}_{delta}"][0])))
    return st


def show(r):
    f = r["fit"]
    rec = "".join("   none  " if v is None else f"{v:>+9.4f}" for v in r["rec"])
    print(f"{r['label']:<38}{rec}  "
          f"slope {f.get('slope', float('nan')):>6.3f}  "
          f"int {f.get('intercept', float('nan')):>+7.3f}  "
          f"adm {r['n_admissible_nonneg']}/5  "
          f"{'mono' if r['monotone'] else 'NOT mono'}")


def main() -> None:
    prob = DeepBeam()
    area = (prob.L / FD.NX) * (prob.H / FD.NY) / 2.0
    same = load_same_solver()
    cross = load_cross()
    fams = [("fixed crack, Q4 40x20", cross), ("same solver, CST", same)]

    betas = [0.0, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50]
    res = {}
    for fname, st in fams:
        print(f"\n{'=' * 108}\n{fname}   (theta = 0, .10, .20, .30, .40)\n")
        rows = [run(st, prob, area, "no tension (baseline)", mode="none")]
        for fct, tag in ((FCT_STRUCT, "f_ct=1.81 struct"),
                         (FCT_EN, "f_ct=2.90 EN")):
            rows.append(run(st, prob, area, f"TCM Marti, {tag}",
                            mode="tcm", f_ct=fct))
        for fct, tag in ((FCT_STRUCT, "1.81"), (FCT_EN, "2.90")):
            for b in betas:
                if b == 0.0 and fct != FCT_STRUCT:
                    continue
                rows.append(run(st, prob, area,
                                f"beta={b:.2f} f_ct={tag} ({b * fct:.2f} MPa)",
                                mode="beta", beta=b, f_ct=fct))
        for b in (0.10, 0.20, 0.30, 0.40):
            rows.append(run(st, prob, area,
                            f"beta={b:.2f} f_ct=1.81 strain-gated",
                            mode="beta", beta=b, f_ct=FCT_STRUCT,
                            gate="strain"))
        for r in rows:
            show(r)
        res[fname] = rows

    OUT.write_text(json.dumps({"families": res, "betas": betas,
                               "f_ct_struct": FCT_STRUCT, "f_ct_en": FCT_EN,
                               "arm_mm": ARM, "delta_mm": float(DELTA),
                               "grid": [float(WIDE[0]), float(WIDE[-1]),
                                        int(WIDE.size)]}, indent=1))
    print(f"\n-> {OUT.relative_to(HERE.parent)}")


if __name__ == "__main__":
    main()
